// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBliv3875udBp2EARP3CTs0iR2t4eIZSU8',
    appId: '1:991144222743:web:42594cfc7086965f6b3c52',
    messagingSenderId: '991144222743',
    projectId: 'flutter-app-gastos',
    authDomain: 'flutter-app-gastos.firebaseapp.com',
    storageBucket: 'flutter-app-gastos.appspot.com',
    measurementId: 'G-7DBWEPP817',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3GbTA_36CGNMrmT5_1-ZIU4pA0ApvP1s',
    appId: '1:991144222743:android:42205eccf780026e6b3c52',
    messagingSenderId: '991144222743',
    projectId: 'flutter-app-gastos',
    storageBucket: 'flutter-app-gastos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsRhYqNmnSh_ovs1cPANFJzbzWJbFd-rc',
    appId: '1:991144222743:ios:bb7877cc6a196bdd6b3c52',
    messagingSenderId: '991144222743',
    projectId: 'flutter-app-gastos',
    storageBucket: 'flutter-app-gastos.appspot.com',
    iosClientId: '991144222743-bh3jma36lsn6fjj5akn26732p57768jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppGastos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsRhYqNmnSh_ovs1cPANFJzbzWJbFd-rc',
    appId: '1:991144222743:ios:bb7877cc6a196bdd6b3c52',
    messagingSenderId: '991144222743',
    projectId: 'flutter-app-gastos',
    storageBucket: 'flutter-app-gastos.appspot.com',
    iosClientId: '991144222743-bh3jma36lsn6fjj5akn26732p57768jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppGastos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBliv3875udBp2EARP3CTs0iR2t4eIZSU8',
    appId: '1:991144222743:web:e9251039d10337c86b3c52',
    messagingSenderId: '991144222743',
    projectId: 'flutter-app-gastos',
    authDomain: 'flutter-app-gastos.firebaseapp.com',
    storageBucket: 'flutter-app-gastos.appspot.com',
    measurementId: 'G-KR2T5L77QV',
  );

}